### ISSUE TITLE
Radius 配置无法成功

### ISSUE THREAD

**Issue by GoKeep** [snipking/docker-ocserv-radius#2]
您好，我按照http://ocserv.gitlab.io/www/recipes-ocserv-authentication-radius-radcli.html所述内容，按照实际修改，发现Radius无法成功
通过docker宿主机用tcpdump抓包发现没有报文。

PS.修改完后依旧可以使用本地认证，通过occtl reload也不行。
请问 有什么需要修改的吗

**Comment by snipking** [comment]
这个 repo 只是在原镜像里面加入了 radcli，因为必须在编译 ocserv 之前加入 radcli 才能令 ocserv 支持 radius 认证。

具体的配置方法请参考 ocserv 的官方文档，也就是你发的那一个，按照那个配置正确一定是可以使用的。

该镜像无法做到开箱即用。

**Comment by GoKeep** [comment]
感谢，我重新试一遍。谢谢
